### ISSUE TITLE
Add AGR tx to CWR Package

### ISSUE THREAD

**Issue by MrTibbles** [kord-network/go-kord#31]
The CWR package needs to add the AGR transaction header to be converted, indexed and available via a graphQL query. 
It is needed as we wish to display the share percentages for each interested party on a work.
The desired fields within each detail record are outlined below.

## TER
* Inclusion/Exclusion indicator
* TIS Numeric Code

## IPA
* Interested party IPI Name #
* IPI base number
* Interested party #
* Interested Party last name
* Interested Party writer first name
* PR affiliation society
* PR share
* MR affiliation society
* MR share

**Comment by orenyodfat** [comment]
SPU also defined the publisher share per NWR 
- SR Ownership Share
- MR Ownership Share
- PR Ownership Share

SWR/OWR also defined the writer share per NWR
- SR Ownership Share
- MR Ownership Share
- PR Ownership Share
