### ISSUE TITLE
Proposed adjustments to the Media API

### ISSUE THREAD

**Issue by MrTibbles** [kord-network/go-kord#51]
`meta:MusicRelease`
- [ ]  CHANGE name to `Song`
- [ ] CHANGE parser to **ignore** `ern:Release:isMainRelease` item
- [ ] ADD: `ern:Duration` as `meta:Duration`
- [ ] ADD: all items within `ern:ReleaseId`, using the `meta:identifiers:[PartyIdentifier]` field syntax
- [ ] CHANGE: `meta:Performers` renamed to `meta:Performer`, with the value changing to the single value from: `ern:DisplayArtistName` || `ern:DisplayArtist`
- [ ] ADD: `meta:RecordLabel`

`meta:MusicProduct`
- [ ] CHANGE name to `meta:MusicRelease`
- [ ] CHANGE parser to **only check for** `ern:Release:isMainRelease` item
- [ ] CHANGE: `meta:Performers` renamed to `meta:Performer`, with the value changing to the single value from: `ern:DisplayArtistName` || `ern:DisplayArtist`
- [ ] ADD: `ern:ReleaseType` as `meta:ReleaseType`
- [ ] ADD: `ern:ReleaseDate` as `meta:ReleaseDate`
- [ ] ADD: all items within `ern:ReleaseId`, using `identifiers: [PartyIdentifier]`
- [ ] ADD: `meta:RecordLabel`

`meta:MusicRecording`
- [ ] CHANGE: `Performers` => `ern:DisplayArtistName` || `ern:DisplayArtist`
- [ ] ADD: `ern:ReleaseReference`
- [ ] ADD: `ern:LabelName`
- [ ] ADD: `ern:ResourceContributor` as `meta:Contributors:[MusicPerformer]`
- [ ] ADD: `ern:Duration` as `meta:Duration`

**Comment by lukehedger** [comment]
Not necessarily for this iteration, but it might be worth exploring how we can move to a standard set of GraphQL query parameters - these can then be used for pagination etc.

For example:
```
filter: Filter
orderBy: OrderBy
skip: Int
after: String
before: String
first: Int
last: Int
```

This is a good article around the topic: https://blog.graph.cool/designing-powerful-apis-with-graphql-query-parameters-8c44a04658a9

**Comment by orenyodfat** [comment]
re : meta:MusicRelease “CHANGE parser to ignore ern:Release:isMainRelease item ” 
Why the filter cannot be done in the dapp level ?

**Comment by MrTibbles** [comment]
Because the request being made to the server will be for all `Song` items, therefore the service should not be polluted with items that are **not** `Song` items.

**Comment by orenyodfat** [comment]
Is there a duration for Song(Release) ? or just for Recording
"ADD: ern:Duration as meta:Duration"

Please clarify this  : "ADD: all items within ern:ReleaseId, using the meta:identifiers:[PartyIdentifier] field syntax"

**Comment by lmars** [comment]
@MrTibbles some questions:

* how should we handle `IsMainRelease` for releases of type `TrackRelease` where there is only one release, should we create both a `Release` and a `Song`? Perhaps create a `Song` if the release has an ISRC?

* do you think it is correct to consider contributors as performers? For example, is the producer of a track a performer?

* why do you want to switch from multiple `Performers` to a single `Performer` on songs? What if there are multiple `DisplayArtist` in the ERN?

* `ReleaseReference` is an internal ERN value, do we really need it in the Media API?

**Comment by MrTibbles** [comment]
> how should we handle IsMainRelease...

If there is only one release item listed in an ERN, and that item is labelled as `IsMainRelease`, then it should be added as a `meta:Release` item. If the `ern:Release` item in question also has an `ISRC` listed, it should be added none the less. 

> do you think it is correct to consider contributors as....

Are you referring to:  "ADD: ern:ResourceContributor as meta:Contributors:[MusicPerformer]"?
If so, i apologise for the oversight and lose of semantic titling. How does `Contributor` or `MusicContributor` sound? IMO `Contributor` as it can be transferred to other media forms by adding a `ContributorType` member, and the `Contributor` will _always_ be a child member of some form of resource (`MusicWork` || `Video` || `MusicRecording`), so "producer" will be understood as one thing(?).

> why do you want to switch from multiple Performers to a single....

My thinking was to handle which one to show in UI, but thinking about it if `ern:ArtistRole` was added, to `meta:MusicPerformer`, it would aid that issue by showing all returned `meta:MusicPerformers`, with their (if present) listed role they played. 

> ADD: ern:ReleaseReference

This was for the track number when part of a release collection. Currently i am simply using the index of the item in the response payload.

My suggestion of using the same approach/similar approach that `meta:PartyIdentifier` uses in `meta:MusicPerformer`, `meta:RecordLabel`, that being an array of objects with a `type` and `value` declaration, for the `ern:ReleaseId` is to handle an arbitrary set of key:value identifiers with varying type and presence. So the `meta:PartyIdentifier` object would need to change to be called `meta:Identifier`, or another object would need to be created called `meta:ItemIdentifier`. Does that make sense? @orenyodfat @lmars

**Comment by lmars** [comment]
@MrTibbles thanks, that clears things up except for:

> > how should we handle IsMainRelease...

> If there is only one release item listed in an ERN, and that item is labelled as IsMainRelease, then it should be added as a meta:Release item. If the ern:Release item in question also has an ISRC listed, it should be added none the less.

What about adding `Song` though? If there is a single release (so has `IsMainRelease=true`) but also has an ISRC because it is a track release, do we insert both a `Release` and a `Song` into the index?

**Comment by lmars** [comment]
The decision is that we will add both a `Release` and a `Song` for track releases.
